version: "3.7"

networks:
  laravel:

volumes:
  database:

services:
  database:
    image: postgres:10
    container_name: postgres
    restart: "no"
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - 5432:5432
    environment:
      
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "DEVJuniorPHP"
      
      
    

  
  

  npm:  
    image: node:12
    working_dir: /var/www/DEVJuniorPHP
    entrypoint: ["npm"]
    volumes: 
    - "./www/:/var/www/DEVJuniorPHP"

  app:
    container_name: app
    restart: "no"
    volumes:
      - ./:/var/www/DEVJuniorPHP
      
    networks:
      - laravel
    depends_on:
      - npm
      
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    
    command: php-fpm

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: "no"
    volumes:
      - ./:/var/www/DEVJuniorPHP
      - ./nginx/default.conf:/etc/nginx/conf.d 
    networks:
      - laravel
    ports:
      - 8000:8000
    depends_on:
      - database
      - app